import { createFileRoute } from "@tanstack/react-router";
import { Clock, Coffee, Copy, Loader2, Sparkles } from "lucide-react";
import { useState } from "react";
import { AppShell, PageHeader } from "@/components/app-shell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Skeleton } from "@/components/ui/skeleton";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { saveHistory } from "@/lib/storage";
import { copyText, extractJson, useAi } from "@/lib/use-ai";

export const Route = createFileRoute("/planner")({
  head: () => ({
    meta: [
      { title: "AI Task Planner | WorkFlow AI" },
      {
        name: "description",
        content:
          "Turn a task list into a time-blocked daily schedule, weekly plan and priority matrix with recommended breaks.",
      },
      { property: "og:title", content: "AI Task Planner | WorkFlow AI" },
      {
        property: "og:description",
        content: "Time-blocked schedules, weekly plans and priority matrices generated by AI.",
      },
    ],
  }),
  component: PlannerPage,
});

type Block = { start: string; end: string; task: string; type: string; priority: string };
type PlanResult = {
  dailySchedule: Block[];
  weeklyPlan: Array<{ day: string; focus: string; tasks: string[] }>;
  matrix: {
    urgentImportant: string[];
    notUrgentImportant: string[];
    urgentNotImportant: string[];
    neitherUrgentNorImportant: string[];
  };
  suggestions: string[];
  breaks: string[];
};

const SYSTEM = `You are an expert productivity planner using time-blocking and Eisenhower prioritisation.
Respond with ONLY a JSON object with keys: dailySchedule (array of objects: start "HH:MM", end "HH:MM", task, type one of Deep Work/Admin/Meeting/Break, priority one of High/Medium/Low), weeklyPlan (array of 5 objects: day, focus, tasks array), matrix (object with urgentImportant, notUrgentImportant, urgentNotImportant, neitherUrgentNorImportant arrays of strings), suggestions (array of 4 strings), breaks (array of 3 strings). Respect the stated working hours.`;

function typeTone(type: string) {
  const t = type?.toLowerCase();
  if (t?.includes("deep")) return "bg-primary/15 text-primary hover:bg-primary/15";
  if (t?.includes("break")) return "bg-success/15 text-success hover:bg-success/15";
  if (t?.includes("meeting")) return "bg-accent/20 text-accent-foreground hover:bg-accent/20";
  return "bg-muted text-muted-foreground hover:bg-muted";
}

function PlannerPage() {
  const { generate, loading } = useAi();
  const [tasks, setTasks] = useState("");
  const [hours, setHours] = useState("09:00 - 17:00");
  const [result, setResult] = useState<PlanResult | null>(null);

  async function run() {
    if (!tasks.trim()) return;
    const text = await generate({
      system: SYSTEM,
      prompt: `Working hours: ${hours}\nTasks with priorities and deadlines:\n${tasks}`,
      json: true,
    });
    if (!text) return;
    const parsed = extractJson<PlanResult>(text);
    if (!parsed) return;
    setResult(parsed);
    saveHistory({
      kind: "plan",
      title: `Schedule for ${hours}`,
      preview: parsed.dailySchedule?.[0]?.task ?? "Generated plan",
      content: JSON.stringify(parsed, null, 2),
    });
  }

  const quadrants = result
    ? ([
        ["Urgent & important", result.matrix?.urgentImportant, "border-destructive/40"],
        ["Important, not urgent", result.matrix?.notUrgentImportant, "border-primary/40"],
        ["Urgent, not important", result.matrix?.urgentNotImportant, "border-warning/50"],
        ["Neither", result.matrix?.neitherUrgentNorImportant, "border-border"],
      ] as const)
    : [];

  return (
    <AppShell>
      <PageHeader
        eyebrow="Feature 03"
        title="AI Task Planner"
        description="Describe your tasks, priorities and deadlines. Get a realistic time-blocked plan that protects deep work."
      />

      <div className="grid grid-cols-1 gap-4 lg:grid-cols-5">
        <section className="glass-card space-y-4 p-5 lg:col-span-2">
          <div className="space-y-2">
            <Label htmlFor="hours">Working hours</Label>
            <Input id="hours" value={hours} onChange={(e) => setHours(e.target.value)} />
          </div>
          <div className="space-y-2">
            <Label htmlFor="tasks">Tasks, priorities and deadlines</Label>
            <Textarea
              id="tasks"
              rows={12}
              className="min-h-64 text-[13px]"
              value={tasks}
              onChange={(e) => setTasks(e.target.value)}
              placeholder={"Finalise Q3 budget — high — due today\nReview design specs — medium — Thursday\nInterview candidate — high — 14:00\nClear support backlog — low — Friday"}
            />
          </div>
          <Button className="w-full" onClick={() => void run()} disabled={loading || !tasks.trim()}>
            {loading ? <Loader2 className="size-4 animate-spin" /> : <Sparkles className="size-4" />}
            Build my plan
          </Button>
        </section>

        <div className="lg:col-span-3">
          {loading && (
            <div className="glass-card space-y-3 p-5">
              {Array.from({ length: 6 }).map((_, i) => (
                <Skeleton key={i} className="h-12 w-full" />
              ))}
            </div>
          )}

          {!loading && !result && (
            <div className="glass-card flex min-h-64 flex-col items-center justify-center gap-2 p-8 text-center">
              <Clock className="size-6 text-accent" aria-hidden />
              <p className="text-sm font-medium">Your schedule will appear here</p>
              <p className="max-w-sm text-xs text-muted-foreground">
                Timeline, weekly plan and priority matrix views, plus recommended recovery breaks.
              </p>
            </div>
          )}

          {!loading && result && (
            <Tabs defaultValue="timeline" className="space-y-4">
              <TabsList>
                <TabsTrigger value="timeline">Timeline</TabsTrigger>
                <TabsTrigger value="week">Weekly</TabsTrigger>
                <TabsTrigger value="matrix">Priority matrix</TabsTrigger>
              </TabsList>

              <TabsContent value="timeline" className="space-y-4">
                <section className="glass-card p-5">
                  <div className="mb-4 flex items-center justify-between">
                    <h2 className="text-sm font-semibold">Time-blocked day</h2>
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() =>
                        void copyText(
                          result.dailySchedule
                            .map((b) => `${b.start}-${b.end} ${b.task} (${b.type})`)
                            .join("\n"),
                        )
                      }
                    >
                      <Copy className="size-4" /> Copy
                    </Button>
                  </div>
                  <ol className="relative space-y-3 border-l border-border pl-5">
                    {result.dailySchedule?.map((b, i) => (
                      <li key={`${b.start}-${i}`} className="relative">
                        <span
                          className="absolute top-3 -left-[26px] size-2.5 rounded-full bg-primary ring-4 ring-background"
                          aria-hidden
                        />
                        <div className="rounded-xl border border-border/70 bg-card/60 p-3">
                          <div className="flex flex-wrap items-center gap-2">
                            <span className="font-mono text-xs text-muted-foreground">
                              {b.start} – {b.end}
                            </span>
                            <Badge className={typeTone(b.type)}>{b.type}</Badge>
                            <Badge variant="outline" className="text-[11px]">
                              {b.priority}
                            </Badge>
                          </div>
                          <p className="mt-1.5 text-sm font-medium">{b.task}</p>
                        </div>
                      </li>
                    ))}
                  </ol>
                </section>

                <div className="grid gap-4 md:grid-cols-2">
                  <section className="glass-card p-5">
                    <h2 className="mb-3 text-sm font-semibold">Productivity suggestions</h2>
                    <ul className="space-y-2 text-sm text-muted-foreground">
                      {result.suggestions?.map((s) => (
                        <li key={s} className="flex gap-2">
                          <Sparkles className="mt-0.5 size-3.5 shrink-0 text-accent" aria-hidden />
                          {s}
                        </li>
                      ))}
                    </ul>
                  </section>
                  <section className="glass-card p-5">
                    <h2 className="mb-3 text-sm font-semibold">Recommended breaks</h2>
                    <ul className="space-y-2 text-sm text-muted-foreground">
                      {result.breaks?.map((s) => (
                        <li key={s} className="flex gap-2">
                          <Coffee className="mt-0.5 size-3.5 shrink-0 text-success" aria-hidden />
                          {s}
                        </li>
                      ))}
                    </ul>
                  </section>
                </div>
              </TabsContent>

              <TabsContent value="week">
                <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">
                  {result.weeklyPlan?.map((d) => (
                    <section key={d.day} className="glass-card p-5">
                      <h3 className="text-sm font-semibold">{d.day}</h3>
                      <p className="text-xs text-accent-foreground/80">{d.focus}</p>
                      <ul className="mt-3 space-y-1.5 text-sm text-muted-foreground">
                        {d.tasks?.map((t) => (
                          <li key={t} className="flex gap-2">
                            <span className="mt-2 size-1.5 shrink-0 rounded-full bg-primary" aria-hidden />
                            {t}
                          </li>
                        ))}
                      </ul>
                    </section>
                  ))}
                </div>
              </TabsContent>

              <TabsContent value="matrix">
                <div className="grid gap-4 sm:grid-cols-2">
                  {quadrants.map(([label, items, border]) => (
                    <section key={label} className={`glass-card border-l-4 p-5 ${border}`}>
                      <h3 className="text-sm font-semibold">{label}</h3>
                      <ul className="mt-3 space-y-1.5 text-sm text-muted-foreground">
                        {(items ?? []).map((t) => (
                          <li key={t}>• {t}</li>
                        ))}
                      </ul>
                    </section>
                  ))}
                </div>
              </TabsContent>
            </Tabs>
          )}
        </div>
      </div>
    </AppShell>
  );
}